from src.content import content_manager

from src.content.contest import Contest
from src.content.app_data import AppData

app_data = AppData()
contest_data = Contest()


# Project info
# Meta info
# Required files:
# content/arabic/quran-uthmani.txt

# content/translations/en.yusufali.txt
# content/translations/en.shakir.txt
# content/translations/ur.maududi.txt
# content/translations/ur.jalandhry.txt
#
# content/metadata/surah_metadata.json - {generated with same name by generate_metadata_mapping.py}
# content/metadata/ruku_to_surah_mapping.json - {former name: ruku_to_surah_map.json, generated by: generate_metadata_mapping.py}
# content/metadata/verse_number_to_root_sequence_mapping.json - {former name: ayah_root_sequence.json, generated by: generate_metadata_mapping.py}
# content/metadata/root_statistics.json - {generated with same name by generate_metadata_mapping.py}

# !!Note: Only file which has not been commited yet.
# content/translations/root-meaning-v2.csv

# Usage following file generate metadata content:
# generate_metadata_mapping.py


if __name__ == "__main__":
    # content_manager.get_ruku_content(app_data, ruku_number)
